services:
  svc-init:
    build:
      context: .
      dockerfile: services/init/Dockerfile
    container_name: svc-init
    restart: "no"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/tkl-chat
    command: >
      sh -c "diesel setup && diesel migration run"
      
  svc-auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    container_name: svc-auth
    depends_on:
      - postgres
    env_file:
      - .env

  svc-friend:
    build:
      context: .
      dockerfile: services/friend/Dockerfile
    container_name: svc-friend
    depends_on:
      - postgres
    env_file:
      - .env

  svc-profile:
    build:
      context: .
      dockerfile: services/profile/Dockerfile
    container_name: svc-profile
    depends_on:
      - postgres
    env_file:
      - .env

  nginx:
    image: nginx:1.27
    container_name: svc-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - svc-auth
      - svc-friend
      - svc-profile
      
  mongo:
    image: mongo:8.0-noble
    restart: always
    container_name: db-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data-dev:/data/db
      - ./schema/mongo:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"

  postgres:
    image: postgres:17.5
    restart: always
    container_name: db-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=tkl-chat
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:8.0
    restart: always
    container_name: db-redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data-dev:/data
    command: sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - "6379:6379"
    
  jaeger:
    image: jaegertracing/jaeger:2.6.0
    container_name: svc-jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - LOG_LEVEL=debug

volumes:
  mongo-data-dev:
  postgres-data-dev:
  redis-data-dev:
