services:
  mongo:
    image: mongo:8.0.9
    restart: always
    container_name: db_mongo_messages
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - ./schema/mongo:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017

  postgres:
    image: postgres:17.5
    restart: always
    container_name: db_postgres_users
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=tkl-chat
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data:
  mongo-data:
